overrides:
  "clean-css@3": "5.3.3"
allowBuilds:
  '@fortawesome/fontawesome-common-types': false
  '@fortawesome/fontawesome-svg-core': false
  '@fortawesome/free-brands-svg-icons': false
  '@fortawesome/free-solid-svg-icons': false
  core-js: false
  fsevents: false
# Minutes after publish before pnpm will install a version. 1440 is one day.
minimumReleaseAge: 1440